name: Build images on tag

permissions:
  packages: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*

jobs:
  build:
    name: Build image
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - "arm64"
          - "amd64"
        base:
          - "buster"
          - "bullseye"

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set env variables
        run: |
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v2

      - name: Run Docker buildx
        run: |
          ./generate-dockerfiles.sh
          docker buildx build --platform linux/${{ matrix.architecture }} \
            --tag ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:${TAG}-${{ matrix.base }}-slim-${{ matrix.architecture }} --output "type=registry" \
            --build-arg arch=${{ matrix.architecture }} \
            --build-arg version=${TAG} \
            --file Dockerfile.${{ matrix.base }} \
            ./

  create-manifest:
    name: Create two-architecture manifest
    runs-on: ubuntu-22.04
    needs: build
    strategy:
      matrix:
        base:
          - "buster"
          - "bullseye"

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set env variables
        run: |
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create final manifest
        run: ./create-manifest.sh "ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}" "${TAG}" "${{ matrix.base }}-slim"
